### ISSUE TITLE
Emails loading as a series of digits and letters

### ISSUE THREAD

**Issue by yvan2024** [apparition47/MailTrackerBlockerApp#21]
**Describe the bug**
Some emails are loading as a series of letters and digits. When opened fully in a new window they sometimes appear as a normal email with images etc. but a number of them just seem to be loading as a series of letter and numbers.

**To Reproduce**
1. Go to 'Mail"
2. Click on 'An email'
3. Scroll down to 'the email'
4. See error 'you will only see a codes of numbers and letters that is continous'

**Expected behavior**
On occasion when a different email is selected the error may not occur. When other times I return to the email with the error the issue seems to be resolved but may affect other emails instead. An example of part of the email.
PGh0bWwgZGlyPSJsdHIiIGxhbmc9ImVuIj4KCiAgPGhlYWQ+CiAgICA8bWV0YSBodHRwLWVxdWl2 PSJDb250ZW50LVR5cGUiIGNvbnRlbnQ9InRleHQvaHRtbDsgY2hhcnNldD11dGYtOCIgLz4KICAg IDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJpbml0aWFsLXNjYWxlPTEuMCxtaW5pbXVt LXNjYWxlPTEuMCxtYXhpbXVtLXNjYWxlPTEuMCx3aWR0aD1kZXZpY2Utd2lkdGgsaGVpZ2h0PWRl dmljZS1oZWlnaHQsdGFyZ2V0LWRlbnNpdHlkcGk9ZGV2aWNlLWRwaSx1c2VyLXNjYWxhYmxlPW5v IiAvPgogICAgPHRpdGxlPllvdXIgUGF5UGFsIFBheSBpbiA0IHBheW1lbnQgd2VudCB0aHJvdWdo PC90aXRsZT4KICAgIDxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+CiAgICAgIC8qKgogKiBQYXlQYWwt T3BlbiBGb250cwogKi8KICAgICAgLyogQm9keSB0ZXh0IC0gZm9udC13ZWlnaHQ6NDAwICovCiAg ICAgIEBmb250LWZhY2UgewogICAgICAgIGZvbnQtZmFtaWx5OiBQYXlQYWwtT3BlbjsKICAgICAg ICBmb250LXN0eWxlOiBub3JtYWw7CiAgICAgICAgZm9udC13ZWlnaHQ6IDQwMDsKICAgICAgICBz cmM6IHVybCgnaHR0cHM6Ly93d3cucGF5cGFsb2JqZWN0cy5jb20vZGlnaXRhbGFzc2V0cy9jL3N5 c3RlbS10cmlnZ2VyZWQtZW1haWwvbi9sYXlvdXQvZm9udHMvUGF5UGFsT3Blbi9QYXlQYWxPcGVu LVJlZ3VsYXIub3RmJykgZm9ybWF0KCJvcGVudHlwZSIpOwogICAgICAgIC8qIElFOSBDb21wYXQg TW9kZXMgKi8KICAgICAgICBzcmM6IHVybCgnaHR0cHM6Ly93d3cucGF5cGFsb2JqZWN0cy5jb20v ZGlnaXRhbGFzc2V0cy9jL3N5c3RlbS10cmlnZ2VyZWQtZW1haWwvbi9sYXlvdXQvZm9udHMvUGF5 UGFsT3Blbi9QYXlQYWxPcGVuLVJlZ3VsYXIud29mZjInKSBmb3JtYXQoJ3dvZmYyJyksCiAgICAg ICAgICAvKk1vZGVybmVyIEJyb3dzZXJzKi8KICAgICAgICAgIHVybCgnaHR0cHM6Ly93d3cucGF5 cGFsb2JqZWN0cy5jb20vZGlnaXRhbGFzc2V0cy9jL3N5c3RlbS10cmlnZ2VyZWQtZW1haWwvbi9s YXlvdXQvZm9udHMvUGF5UGFsT3Blbi9QYXlQYWxPcGVuLVJlZ3VsYXIud29mZicpIGZvcm1hdCgn d29mZicpOwogICAgICAgIC8qIE1vZGVybiBCcm93c2VycyAqLwogICAgICAgIC8qIEZhbGxiYWNr IGZvbnQgZm9yIC0gTVMgT3V0bG9vayBvbGRlciB2ZXJzaW9ucyAoMjAwNywxMywgMTYpKi8KICAg ICAgICBtc28tZm9udC1hbHQ6ICdDYWxpYnJpJzsKICAgICAgfQoKICAgICAgLyogSGVhZGxpbmUv U3ViaGVhZGxpbmUvQnV0dG9uIHRleHQgZm9udC13ZWlnaHQ6NTAwICovCiAgICAgIEBmb250LWZh Y2UgewogICAgICAgIGZvbnQtZmFtaWx5OiBQYXlQYWwtT3BlbjsKICAgICAgICBmb250LXN0eWxl OiBub3JtYWw7CiAgICAgICAgZm9udC13ZWlnaHQ6IDUwMDsKICAgICAgICBzcmM6IHVybCgnaHR0 cHM6Ly93d3cucGF5cGFsb2JqZWN0cy5jb20vZGlnaXRhbGFzc2V0cy9jL3N5c3RlbS10cmlnZ2Vy ZWQtZW1haWwvbi9sYXlvdXQvZm9udHMvUGF5UGFsT3Blbi9QYXlQYWxPcGVuLU1lZGl1bS5vdGYn KSBmb3JtYXQoIm9wZW50eXBlIik7CiAgICAgICAgLyogSUU5IENvbXBhdCBNb2RlcyAqLwogICAg ICAgIHNyYzogdXJsKCdodHRwczovL3d3dy5wYXlwYWxvYmplY3RzLmNvbS9kaWdpdGFsYXNzZXRz L2Mvc3lzdGVtLXRyaWdnZXJlZC1lbWFpbC9uL2xheW91dC9mb250cy9QYXlQYWxPcGVuL1BheVBh bE9wZW4tTWVkaXVtLndvZmYyJykgZm9ybWF0KCd3b2ZmMicpLAogICAgICAgICAgLypNb2Rlcm5l ciBCcm93c2VycyovCiAgICAgICAgICB1cmwoJ2h0dHBzOi8vd3d3LnBheXBhbG9iamVjdHMuY29t L2RpZ2l0YWxhc3NldHMvYy9zeXN0ZW0tdHJpZ2dlcmVkLWVtYWlsL24vbGF5b3V0L2ZvbnRzL1Bh eVBhbE9wZW4vUGF5UGFsT3Blbi1NZWRpdW0ud29mZicpIGZvcm1hdCgnd29mZicpOwogICAgICAg IC8qIE1vZGVybiBCcm93c2VycyAqLwogICAgICAgIC8qIEZhbGxiYWNrIGZvbnQgZm9yIC0gTVMg T3V0bG9vayBvbGRlciB2ZXJzaW9ucyAoMjAwNywxMywgMTYpKi8KICAgICAgICBtc28tZm9udC1h bHQ6ICdDYWxpYnJpJzsKICAgICAgfQoKICAgICAgLyogQm9sZCB0ZXh0IC0gPGI+LCA8c3Ryb25n PiBCb2xkIGVxdWFscyB0byBmb250LXdlaWdodDo3MDAgKi8KICAgICAgQGZvbnQtZmFjZSB7CiAg ICAgICAgZm9udC1mYW1pbHk6IFBheVBhbC1PcGVuOwogICAgICAgIGZvbnQtc3R5bGU6IG5vcm1h bDsKICAgICAgICBmb250LXdlaWdodDogNzAwOwogICAgICAgIHNyYzogdXJsKCdodHRwczovL3d3 dy5wYXlwYWxvYmplY3RzLmNvbS9kaWdpdGFsYXNzZXRzL2Mvc3lzdGVtLXRyaWdnZXJlZC1lbWFp bC9uL2xheW91dC9mb250cy9QYXlQYWxPcGVuL1BheVBhbE9wZW4tQm9sZC5vdGYnKSBmb3JtYXQo Im9wZW50eXBlIik7CiAgICAgICAgLyogSUU5IENvbXBhdCBNb2RlcyAqLwogICAgICAgIHNyYzog dXJsKCdodHRwczovL3d3dy5wYXlwYWxvYmplY3RzLmNvbS9kaWdpdGFsYXNzZXRzL2Mvc3lzdGVt LXRyaWdnZXJlZC1lbWFpbC9uL2xheW91dC9mb250cy9QYXlQYWxPcGVuL1BheVBhbE9wZW4tQm9s ZC53b2ZmMicpIGZvcm1hdCgnd29mZjInKSwKICAgICAgICAgIC8qTW9kZXJuZXIgQnJvd3NlcnMq LwogICAgICAgICAgdXJsKCdodHRwczovL3d3dy5wYXlwYWxvYmplY3RzLmNvbS9kaWdpdGFsYXNz ZXRzL2Mvc3lzdGVtLXRyaWdnZXJlZC1lbWFpbC9uL2xheW91dC9mb250cy9QYXlQYWxPcGVuL1Bh eVBhbE9wZW4tQm9sZC53b2ZmJykgZm9ybWF0KCd3b2ZmJyk7CiAgICAgICAgLyogTW9kZXJuIEJy b3dzZXJzICovCiAgICAgICAgLyogRmFsbGJhY2sgZm9udCBmb3IgLSBNUyBPdXRsb29rIG9sZGVy IHZlcnNpb25zICgyMDA3LDEzLCAxNikqLwogICAgICAgIG1zby1mb250LWFsdDogJ0NhbGlicmkn OwogICAgICB9CgogICAgICAvKiBFbmQgLSBQYXlQYWwtT3BlbiBGb250cyAqLwoKICAgICAgLyoq CiAqIFZYLUxJQiBTdHlsZXMgCiAqIEltcG9ydCBvbmx5IHRoZSBzdHlsZXMgcmVxdWlyZWQgZm9y IEVtYWlsIHRlbXBsYXRlcy4KICovCiAgICAgIEBjaGFyc2V0ICJVVEYtOCI7CgogICAgICBodG1s IHsKICAgICAgICBib3gtc2l6aW5nOiBib3JkZXItYm94OwogICAgICB9CgogICAgICAqLAogICAg ICAqOmJlZm9yZSwKICAgICAgKjphZnRlciB7CiAgICAgICAgYm94LXNpemluZzogaW5oZXJpdDsK ICAgICAgfQoKICAgICAgLyogU2V0dGluZyB0aGVzZSBlbGVtZW50cyB0byBoZWlnaHQgb2YgMTAw JSBlbnN1cmVzIHRoYXQKICogLnZ4X2ZvcmVncm91bmQtY29udGFpbmVyIGZ1bGx5IGNvdmVycyB0 aGUgd2hvbGUgdmlld3BvcnQKICovCiAgICAgIGh0bWwsCiAgICAgIGJvZHkgewogICAgICAgIGhl aWdodDogMTAwJTsKICAgICAgfQoKICAgICAgYm9keSB7CiAgICAgICAgZm9udC1zaXplOiAxNHB4 ICFpbXBvcnRhbnQ7CiAgICAgICAgZm9udC1mYW1pbHk6IFBheVBhbC1PcGVuLCAnSGVsdmV0aWNh IE5ldWUnLCBIZWx2ZXRpY2EsIEFyaWFsLCBzYW5zLXNlcmlmOwogICAgICAgIC13ZWJraXQtZm9u dC1zbW9vdGhpbmc6IGFudGlhbGlhc2VkOwogICAgICAgIC1tb3otb3N4LWZvbnQtc21vb3RoaW5n OiBncmF5c2NhbGU7CiAgICAgICAgZm9udC1zbW9vdGhpbmc6IGFudGlhbGlhc2VkOwogICAgICB9 CgogICAgICBhLAogICAgICBhOnZpc2l0ZWQgewogICAgICAgIGNvbG9yOiAjMDA3MEUwOwogICAg ICAgIHRleHQtZGVjb3JhdGlvbjogbm9uZTsKICAgICAgICBmb250LXdlaWdodDogNTAwOwogICAg ICAgIGZvbnQtZmFtaWx5OiBQYXlQYWwtT3BlbiwgJ0hlbHZldGljYSBOZXVlJywgSGVsdmV0aWNh LCBBcmlhbCwgc2Fucy1zZXJpZjsKICAgICAgfQoKICAgICAgYTphY3RpdmUsCiAgICAgIGE6Zm9j dXMsCiAgICAgIGE6aG92ZXIgewogICAgICAgIGNvbG9yOiAjMDAzMDg3OwogICAgICAgIHRleHQt ZGVjb3JhdGlvbjogdW5kZXJsaW5lOwogICAgICB9CgogICAgICBwLAogICAgICBsaSwKICAgICAg ZGQsCiAgICAgIGR0LAogICAgICBsYWJlbCwKICAgICAgaW5wdXQsCiAgICAgIHRleHRhcmVhLAog ICAgICBwcmUsCiAgICAgIGNvZGUsCiAgICAgIHRhYmxlIHsKICAgICAgICBmb250LXNpemU6IDE0 cHg7CiAgICAgICAgbGluZS1oZWlnaHQ6IDEuNjsKICAgICAgICBmb250LXdlaWdodDogNDAwOwog ICAgICAgIHRleHQtdHJhbnNmb3JtOiBub25lOwogICAgICAgIGZvbnQtZmFtaWx5OiBQYXlQYWwt T3BlbiwgJ0hlbHZldGljYSBOZXVlJywgSGVsdmV0aWNhLCBBcmlhbCwgc2Fucy1zZXJpZjsKICAg ICAgICBjb2xvcjogIzAwMTQzNTsKICAgICAgfQoKICAgICAgLnZ4X2xlZ2FsLXRleHQgewogICAg ICAgIGZvbnQtc2l6ZTogMC44MTI1cmVtOwogICAgICAgIGxpbmUtaGVpZ2h0OiAxLjM4NDYxNTM4 OwogICAgICAgIGZvbnQtd2VpZ2h0OiA0MDA7CiAgICAgICAgdGV4dC10cmFuc2Zvcm06IG5vbmU7 CiAgICAgICAgZm9udC1mYW1pbHk6IFBheVBhbC1PcGVuLCAnSGVsdmV0aWNhIE5ldWUnLCBIZWx2 ZXRpY2EsIEFyaWFsLCBzYW5zLXNlcmlmOwogICAgICAgIGNvbG9yOiAjNmM3Mzc4OwogICAgICB9 CgogICAgICAvKiBFbmQgLSBWWC1MSUIgU3R5bGVzICovCgogICAgICAvKioKICogU3R5bGVzIGZy b20gTmVwdHVuZQogKi8KICAgICAgLyogcHJldmVudCBpT1MgZm9udCB1cHNpemluZyAqLwogICAg ICAqIHsKICAgICAgICAtd2Via2l0LXRleHQtc2l6ZS1hZGp1c3Q6IG5vbmU7CiAgICAgIH0KCiAg ICAgIC8qIGZvcmNlIE91dGxvb2suY29tIHRvIGhvbm9yIGxpbmUtaGVpZ2h0ICovCiAgICAgIC5F eHRlcm5hbENsYXNzICogewogICAgICAgIGxpbmUtaGVpZ2h0OiAxMDAlOwogICAgICB9CgogICAg ICB0ZCB7CiAgICAgICAgbXNvLWxpbmUtaGVpZ2h0LXJ1bGU6IGV4YWN0bHk7CiAgICAgIH0KCiAg ICAgIC8qIHByZXZlbnQgaU9TIGF1dG8tbGlua2luZyAqLwogICAgICAvKiBBbmRyb2lkIG1hcmdp biBmaXggKi8KICAgICAgYm9keSB7CiAgICAgICAgbWFyZ2luOiAwOwogICAgICAgIHBhZGRpbmc6 IDA7CiAgICAgIH0KCiAgICAgIGRpdltzdHlsZSo9Im1hcmdpbjogMTZweCAwIl0gewogICAgICAg IG1hcmdpbjogMCAhaW1wb3J0YW50OwogICAgICB9CgogICAgICAvKiogUHJldmVudCBPdXRsb29r IFB1cnBsZSBMaW5rcyAqKi8KICAgICAgLmdyZXlMaW5rIGE6bGluayB7CiAgICAgICAgY29sb3I6 ICM5NDk1OTU7CiAgICAgIH0KCiAgICAgIC8qIHByZXZlbnQgaU9TIGF1dG8tbGlua2luZyAqLwog ICAgICAuYXBwbGVmaXggYSB7CiAgICAgICAgLyogdXNlIG9uIGEgc3BhbiBhcm91bmQgdGhlIHRl eHQgKi8KICAgICAgICBjb2xvcjogaW5oZXJpdDsKICAgICAgICB0ZXh0LWRlY29yYXRpb246IG5v bmU7CiAgICAgIH0KCiAgICAgIC5wcHNhbnMgewogICAgICAgIGZvbnQtZmFtaWx5OiBQYXlQYWwt T3BlbiwgJ0hlbHZldGljYSBOZXVlJywgSGVsdmV0aWNhLCBBcmlhbCwgc2Fucy1zZXJpZiAhaW1w b3J0YW50OwogICAgICB9CgogICAgICAvKiB1c2UgdG8gbWFrZSBpbWFnZSBzY2FsZSB0byAxMDAg cGVyY2VudCAqLwogICAgICAubXBpZGl2IGltZyB7CiAgICAgICAgd2lkdGg6IDEwMCU7CiAgICAg ICAgaGVpZ2h0OiBhdXRvOwogICAgICAgIG1pbi13aWR0aDogMTAwJTsKICAgICAgICBtYXgtd2lk dGg6IDEwMCU7CiAgICAgIH0KCiAgICAgIC5zdGFja1RibCB7CiAgICAgICAgd2lkdGg6IDEwMCU7 CiAgICAgICAgZGlzcGxheTogdGFibGU7CiAgICAgIH0KCiAgICAgIC8qIFJlc3BvbnNpdmUgQ1NT ICovCiAgICAgIEBtZWRpYSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDY0MHB4KSB7CgogICAgICAg IC8qKiogSW1hZ2UgV2lkdGggU3R5bGVzICoqKi8KICAgICAgICAuaW1nV2lkdGggewogICAgICAg ICAgd2lkdGg6IDIwcHggIWltcG9ydGFudDsKICAgICAgICB9CiAgICAgIH0KCiAgICAgIEBtZWRp YSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDQ4MHB4KSB7CgogICAgICAgIC8qKiogSW1hZ2UgV2lk dGggU3R5bGVzICoqKi8KICAgICAgICAuaW1nV2lkdGggewogICAgICAgICAgd2lkdGg6IDEwcHgg IWltcG9ydGFudDsKICAgICAgICB9CiAgICAgIH0KCiAgICAgIC8qIEVuZCAtIFJlc3BvbnNpdmUg Q1NTICovCgogICAgICAvKiBGaXggZm9yIE5lcHR1bmUgcGFydG5lciBsb2dvICovCiAgICAgIC5w YXJ0bmVyX2ltYWdlIHsKICAgICAgICBtYXgtd2lkdGg6IDI1MHB4OwogICAgICAgIG1heC1oZWln aHQ6IDkwcHg7CiAgICAgICAgZGlzcGxheTogYmxvY2s7CiAgICAgIH0KCiAgICAgIC8qIEVuZCAt IFN0eWxlcyBmcm9tIE5lcHR1bmUgKi8KCiAgICAgIC8qKgogKiBTdHlsZXMgLSBvdmVycmlkZXMg Zm9yIFBheVBhbCByZWJyYW5kaW5nCiAqLwogICAgICBodG1sLAogICAgICBib2R5IHsKICAgICAg ICBiYWNrZ3JvdW5kOiAjRkFGOEY1OwogICAgICAgIGNvbG9yOiAjMDAxNDM1OwogICAgICAgIGZv bnQtc2l6ZTogMTRweDsKICAgICAgICBsaW5lLWhlaWdodDogMS42OwogICAgICB9CgogICAgICAu Zm9vdGVyRGl2aWRlciB7CiAgICAgICAgbWFyZ2luOiAwcHggMzVweDsKICAgICAgfQoKICAgICAg LyogQnV0dG9uICAqLwogICAgICB0ZC5wYXlwYWwtYnV0dG9uLXByaW1hcnk6aG92ZXIgewogICAg ICAgIC8qU2V0dGluZyBib3JkZXIgdG8gdGQgd291bGQgaW5jcmVhc2UgdGhlIGJ1dHR0b24gc2l6 ZSBvbiBob3ZlciAqLwogICAgICAgIGJhY2tncm91bmQtY29sb3I6ICMwMDcwRTAgIWltcG9ydGFu dDsKICAgICAgfQoKICAgICAgYS5wYXlwYWwtYnV0dG9uLXByaW1hcnk6aG92ZXIgewogICAgICAg IGJhY2tncm91bmQtY29sb3I6ICMwMDcwRTAgIWltcG9ydGFudDsKICAgICAgICBib3JkZXI6IDJw eCBzb2xpZCAjMDA3MEUwICFpbXBvcnRhbnQ7CiAgICAgIH0KCiAgICAgIGEucGF5cGFsLWJ1dHRv bi1zZWNvbmRhcnk6aG92ZXIgewogICAgICAgIGJvcmRlcjogMnB4IHNvbGlkICMwMDcwRTAgIWlt cG9ydGFudDsKICAgICAgICBjb2xvcjogIzAwNzBFMCAhaW1wb3J0YW50OwogICAgICB9CgogICAg ICBhLnBheXBhbC1idXR0b24tYnJhbmRlZDpob3ZlciB7CiAgICAgICAgYmFja2dyb3VuZC1jb2xv cjogI0ZGRTg4OCAhaW1wb3J0YW50OwogICAgICAgIGJvcmRlcjogMnB4IHNvbGlkICNGRkU4ODgg IWltcG9ydGFudDsKICAgICAgfQoKICAgICAgLyoqCiAqIFN0eWxlcyBmb3IgRGFyayBtb2RlCiAq LwogICAgICBAbWVkaWEgKHByZWZlcnMtY29sb3Itc2NoZW1lOiBkYXJrKSB7CgogICAgICAgIC8q IFdyYXAgZW50aXJlIGxvZ28gd2l0aCBib3JkZXIgKi8KICAgICAgICAuZm9vdGVyRGl2aWRlciB7 CiAgICAgICAgICBtYXJnaW4tbGVmdDogMHB4CiAgICAgICAgfQogICAgICB9CiAgICA8L3N0eWxl PgogIDwvaGVhZD4KCiAgPGJvZHk+CiAgICA8aDQgaWQ9InByZUhlYWRlciIgc3R5bGU9ImRpc3Bs YXk6bm9uZTtjb2xvcjojRkFGOEY1O2ZvbnQtc2l6ZTowcHg7bGluZS1oZWlnaHQ6MHB4Ij5JdmFu IEx1Y2ljLUpvemFrLCB0aGFua3MgZm9yIHlvdXIgcGF5bWVudC48L2g0PgogICAgPHRhYmxlIGNl bGxQYWRkaW5nPSIwIiBjZWxsU3BhY2luZz0iMCIgYm9yZGVyPSIwIiB3aWR0aD0iMTAwJSI+CiAg ICAgIDx0Ym9keT4KICAgICAgICA8dHI+CiAgICAgICAgICA8dGQgYmdjb2xvcj0iI0ZBRjhGNSIg c3R5bGU9ImZvbnQtc2l6ZTowcHgiPjwvdGQ+CiAgICAgICAgICA8dGQgYmdjb2xvcj0iI0ZBRjhG NSIgd2lkdGg9IjY0MCIgYWxpZ249ImNlbnRlciIgY2xhc3M9Im1vYkNvbnRlbnQiPgogICAgICAg ICAgICA8dGFibGUgY2VsbFBhZGRpbmc9IjAiIGNlbGxTcGFjaW5nPSIwIiBib3JkZXI9IjAiIHdp ZHRoPSIxMDAlIiBkaXI9Imx0ciI+CiAgICAgICAgICAgICAgPHRib2R5PgogICAgICAgICAgICAg ICAgPHRyPgogICAgICAgICAgICAgICAgICA8dGQ+CiAgICAgICAgICAgICAgICAgICAgPHRhYmxl IGNlbGxQYWRkaW5nPSIwIiBjZWxsU3BhY2luZz0iMCIgYm9yZGVyPSIwIiB3aWR0aD0iMTAwJSI+ CiAgICAgICAgICAgICAgICAgICAgICA8dGJvZHk+CiAgICAgICAgICAgICAgICAgICAgICAgIDx0 cj4KICAgICAgICAgICAgICAgICAgICAgICAgICA8dGQ+CiAgICAgICAgICAgICAgICAgICAgICAg ICAgICA8dGFibGUgd2lkdGg9IjEwMCUiIGNlbGxQYWRkaW5nPSIwIiBjZWxsU3BhY2luZz0iMCIg Ym9yZGVyPSIwIiBzdHlsZT0iYmFja2dyb3VuZDojZmZmIiBkaXI9Imx0ciI+CiAgICAgICAgICAg ICAgICAgICAgICAgICAgICAgIDx0Ym9keT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg ICA8dHI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dGQgc3R5bGU9ImNvbG9y OiM2ODcxNzM7Zm9udC13ZWlnaHQ6NTAwO2ZvbnQtc2l6ZToxNHB4O2xpbmUtaGVpZ2h0OjIwcHg7 cGFkZGluZzoxMHB4Ij48c3Bhbj5IaSBJdmFuIEx1Y2ljLUpvemFrLDwvc3Bhbj48L3RkPgogICAg ICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvdHI+CiAgICAgICAgICAgICAgICAgICAgICAg ICAgICAgIDwvdGJvZHk+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L3RhYmxlPgogICAg

**Logs**
If applicable, please send me the affected email. You can do this by selecting the email, File > Save As... > Format: Raw Message Source. You can then send that `.eml` file to my email in my profile ([@apparition47](https://github.com/apparition47)).

**Environment (please complete the following information):**
 - OS: 15.0 Beta (24A5298h)
 - MailTrackerBlocker version: 1.1.6 (49)

**Additional context**
Issue has started occurring since upgrading to MacOS Beta Version.

**Comment by apparition47** [comment]
This issue didn't happen on macOS Sonoma?

And this happens to some specific emails?

**Comment by yvan2024** [comment]
Hi Aaron

The issue occurred on Sonoma and it only affects some emails intermittently.

Cheers
Yvan




On 30 Jul 2024, at 21:29, Aaron Lee ***@***.***> wrote:


This issue didn't happen on macOS Sonoma?

And this happens to some specific emails?

**Comment by apparition47** [comment]
Would you be able to provide a `eml` file sample for me to look at? You can do that by going to Mail > File > Save As > (Raw Message Source).

**Comment by yvan2024** [comment]
Hi Aaron

Find the file attached for further rectification of error.

Cheers
Yvan
￼

On 30 Jul 2024, at 21:37, Aaron Lee ***@***.***> wrote:


Would you be able to provide a eml file sample for me to look at? You can do that by going to Mail > File > Save As > (Raw Message Source).

**Comment by apparition47** [comment]
It won't show up when you reply to GitHub.

Can you please email it to aaron+github@onefatgiraffe.com?

**Comment by apparition47** [comment]
Sorry, just realized your emails got caught up in my spam filter.

Your PayPal email needs to be in `eml` format for me to verify but I was able to check out the other eml newsletter and it rendered fine on my end (Sonoma 14.5, MailTrackerBlocker 1.1.6):
![image](https://github.com/user-attachments/assets/e967b988-abad-4db1-b83f-2e08d7f904b8)

Just to double check again, are you using the latest **1.1.6** from the App Store? I'll see if I can test it out on the 15.0 betas

**Comment by Bob16180** [comment]
I'm having the same issue. It does seem to load at some point.

**Comment by apparition47** [comment]
@Bob16180 Which version of MailTrackerBlocker are you running?

**Comment by Bob16180** [comment]
I sent you an .elm to the email address I have. I am running 1.1.7.

**Comment by apparition47** [comment]
Thanks, was able to reproduce the issue on Sequoia 15.0. Weird that same eml doesn't exhibit this bug on my main Sonoma 14.7 machine. Looking into it. I recommend using the Content Blocker extension for the time being.

**Comment by apparition47** [comment]
Fixed in 1.1.8

**Comment by yvan2024** [comment]
Hi Aaron 

I have noticed two extensions now in my Mail setting. Can you please explain their purpose? Can I delete one while you create the 1.1.8 version?

Regards
Ivan 



On 30 Sep 2024, at 00:47, Aaron Lee ***@***.***> wrote:


Fixed in 1.1.8

**Comment by yvan2024** [comment]
Hi Aaron

Apologies I forgot to include the screenshot. Can I get rid of one of the extensions or do I keep them both? When is version 1.1.8 being released?

Regards
Ivan 

￼

On 30 Sep 2024, at 00:47, Aaron Lee ***@***.***> wrote:


Fixed in 1.1.8

**Comment by apparition47** [comment]
Apple approved my release 4h ago so you should see be able to see it in the store now.

You can disable the `MailTrackerBlocker` extension and enable `Content Blocker` instead if you're having issues like #2 or #20. It's a lighter version of the extension but lacks all the features of the main `MailTrackerBlocker` extension.

**Comment by yvan2024** [comment]
Hi Aaron

Thank you for your prompt response. Much appreciated!

Cheers
Ivan



On 1 Oct 2024, at 10:58, Aaron Lee ***@***.***> wrote:


Apple approved my release 4h ago so you should see be able to see it in the store now.

You can disable the MailTrackerBlocker extension and enable Content Blocker instead if you're having issues like #2 <https://github.com/apparition47/MailTrackerBlockerApp/issues/2> or #20 <https://github.com/apparition47/MailTrackerBlockerApp/issues/20>. It's a lighter version of the extension but lacks all the features of the main MailTrackerBlocker extension.

**Comment by apparition47** [comment]
Another user reported 1.1.8 doesn't completely fix the issue (#24). 1.1.9 should hopefully fix it this time.
